apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-php
spec:
  selector:
   matchLabels:
    app: apache-php
  replicas: 1
  template:
    metadata:
      labels:
        app: apache-php
    spec:
      containers:
        - name: apache-php
          image: egonzalez2511/php7_apache:latest  
          ports:
            - containerPort: 80
              name: apachephpport
---
kind: Service
apiVersion: v1
metadata:
  name: apache-php-service
  labels:
    app: apache-php
spec:   
  ports:
  - name: apache-php
    port: 80
    nodePort : 31785 
  #type: LoadBalancer
  type: NodePort
  selector:
   app: apache-php